### ISSUE TITLE
[Request] Can you make a version of your morden-x work with the original mpv_thumbnail_script instead of the Thumbnailer?

### ISSUE THREAD

**Issue by ThomasEricB** [dexeonify/mpv-config#1]
You are my only hope Obi-Wan Kenobi!

I've been using both jamesxmcintosh's (https://gist.github.com/jamesxmcintosh) and marzzzello's (https://github.com/marzzzello/mpv_thumbnail_script/) updated versions of the mpv_thumbnail_script and they work great with mpv.net. However, the problem is that they are not updated to the newer versions of the OSC.lua that display the chapter names when you hover with the mouse on the seekbar! I've even brought this issue up in the MPV subreddit recently (hoping someone kind enough could help me out): https://old.reddit.com/r/mpv/comments/rpyy6q/request_can_someone_update_the_mpv_thumbnail/ .

And so I set out to find a way to solve this issue! When I saw that you made a version of the morden-x work that not only work the Thumbnailer but also features the recent osc.lua changes, I was so glad! However, unfortunately, Thumbnailer refuses to generate thumbnails with ffmpeg (for some reason) and mpv.net. And yes, I've even changed line 298 ( worker_extra.index_name = concat_args(args, worker_options.exec_path .. 'mpvnet')) to account for the mpvnet command! Looking at my log.txt didn't show any issues or errors. And thus I've been stuck.

So, I ask you, for the reasons I wrote above, to please consider making a version of the morden-x for the original mpv_thumbnail_script, so it may work with mpv.net. Thank you for reading this.

Thomas

**Comment by ThomasEricB** [comment]
UPDATE: Marzzzello just updated the OSC, but I still feel like this would be great since the morden-x osc is way better looking than the default one.

**Comment by dexeonify** [comment]
This seems to work well.
![image](https://user-images.githubusercontent.com/72267349/147867813-84e3f17e-afb0-4536-9c5d-01a13b1a4d08.png)

The patched files:
[mpv_thumbnail_script-modernx.zip](https://github.com/dexeonify/mpv-config/files/7798654/mpv_thumbnail_script-modernx.zip)

`mpv_thumbnail_script_client_osc.lua` isn't needed because it's already baked into `modernx.lua`. Not sure if you are fine with the icons, the original morden-x used material design icons.

I also did a quick test of `Thumbnailer.lua` in mpv.net. It loaded the thumbnails, but it will regenerate thumbnails every time the player enters/exit fullscreen. ¯\\\_(ツ)\_/¯

**Comment by ThomasEricB** [comment]
Thank you! Thank you so much!!! I'm going to fork your project tomorrow!

**Comment by ThomasEricB** [comment]
Just tested it and it works great! 
![mpvnet_sQ1ko40Xz3](https://user-images.githubusercontent.com/9662095/147870231-1b68256c-ced9-4d8a-a813-37a9ed12a68c.jpg)
 
I also posted on reddit: https://old.reddit.com/r/mpv/comments/ru5a9s/release_mordenx_with_mpv_thumbnail_script_client/?

**Comment by dexeonify** [comment]
That's cool. ❤️
This is gotta be the longest fork chain I've ever seen (4), lol.

I'm also going to just ping this here maoiscat/mpv-osc-morden#1 since this is what originally inspired me to merge them together.

**Comment by ThomasEricB** [comment]
> That's cool. ❤️ This is gotta be the longest fork chain I've ever seen (4), lol.

Hey I just finished setting up my fork at [ThomasEricB/MpvNet-HQ-Config](https://github.com/ThomasEricB/MpvNet-HQ-Config/). I recommend you checking my mpv.conf out (even if it doesn't entirely suit you), it's based on a long research made by me and you might be interested in adding some of those settings in yours too. 

Thank you for your kindness.
