### ISSUE TITLE
[ModernX] showtitle user option is not implemented

### ISSUE THREAD

**Issue by pintassilgo** [dexeonify/mpv-config#5]
Despite being present in code as an user option

https://github.com/dexeonify/mpv-config/blob/9679575d20a40ba741b50d0af5c5f6649d111daf/scripts/modernx.lua#L63

`showtitle` isn't actually implemented.

To fix that, I just added
```lua
ne.visible = user_opts.showtitle
```
after element declaration
https://github.com/dexeonify/mpv-config/blob/9679575d20a40ba741b50d0af5c5f6649d111daf/scripts/modernx.lua#L1760

**Comment by dexeonify** [comment]
Good catch! Apparently, I removed it in 5f9c428 while I was blanket deleting codes.
