### ISSUE TITLE
Can't seem to make thumbnailing work on windows

### ISSUE THREAD

**Issue by lostb053** [dexeonify/mpv-config#7]
Well, I would be grateful if you could help me set up thumbnailer, I just can't seem to get it right.
My problem is, when I add mpv_thumbnailer_script from [this repo](https://github.com/ThomasEricB/Mpv.Net-HQ-Config), the icons get messed up. First I was using ur modernx then switched to his Modern-X, but both give same issues with different results (I mean the icons are messed up in different way for both). But yes thumbnailing works

I'm using mpv I believe, I'm not sure what mpv.net refers to on Win11 64-bit

I'm quite a newbie on mpv. I can't tinker around much with it yet with lack of knowledge of osc scripts and lua language

**Comment by dexeonify** [comment]
> I'm using mpv I believe, I'm not sure what mpv.net refers to on Win11 64-bit

[mpv.net](https://github.com/stax76/mpv.net/) refers to the popular mpv front-end for Windows. Since you are using mpv, I see no reason to use mpv_thumbnail_script; instead, use [Thumbnailer.lua](https://github.com/deus0ww/mpv-conf). You can either download from my repo (includes some of my local enhancements 😉) or download it from upstream (deus0ww's).

> My problem is, when I add mpv_thumbnailer_script from [this repo](https://github.com/ThomasEricB/Mpv.Net-HQ-Config), the icons get messed up.

That repo is massively outdated btw, though it should still work provided that you don't care about recent updates. If you are not using mpv_thumbnail_script, I don't recommend that repo.

> (I mean the icons are messed up in different way for both). But yes thumbnailing works

I'm assuming the icon are just blank hollow boxes? If so, then you did not install the [modernx-osc-icon.ttf](https://github.com/dexeonify/mpv-config/raw/main/modernx-osc-icon.ttf) icon font. You can either install it to your system or create a fonts folder and place it there.

When done correctly, the folder structure should look like this:
```
<your mpv profile folder>
│   input.conf
│   mpv.conf
│
├── fonts/
│   └─ modernx-osc-icon.ttf
│
├── script-opts/
│   ├─ osc.conf
│   └─ thumbnailer.conf
│
└── scripts/
     ├─ modernx.lua
     ├─ Thumbnailer.lua
     └─ Thumbnailer_Worker.lua
```

**Comment by lostb053** [comment]
Your Thumbnailer.lua seemed unresponsive (not sure if it requires trigger, I tried using trigger as stated in `input.conf`, but nothing works).

Well, icons were swapped, not hollow boxes, to add to that, installing your font was first thing i did.

Will later revert file structure to work with `Thumbnailer.lua` when i can access my lap again (travelling). Earlier it was pretty much exact copy of your structure on your repo with latest commit

**Comment by dexeonify** [comment]
> Your Thumbnailer.lua seemed unresponsive (not sure if it requires trigger, I tried using trigger as stated in input.conf, but nothing works).

Did you went through the [config file](https://github.com/dexeonify/mpv-config/blob/main/script-opts/thumbnailer.conf)? There's 2 options (`auto_gen` and `auto_show`) which controls that. Enable both settings if you want it to work out of the box.

I have both settings disabled, so you need to press <kbd>Shift</kbd>+<kbd>T</kbd> to start the Thumbnailer and then press <kbd>'</kbd> to display the Thumbnailer OSC.

> Well, icons were swapped, not hollow boxes, to add to that, installing your font was first thing i did.

That's odd. My only guess is that the modernx-icon-font isn't in sync with modernx's version. A screenshot would help immensely though. Make sure to not mix my icon font with ThomasEricB's.

**Comment by dexeonify** [comment]
I just realized that the link to icon font has been broken for ages ¯\\\_(ツ)_/¯

**Comment by lostb053** [comment]
Lol, well thanks for your response.
Will try the changes recommended by tomorrow and report accordingly. I didn't install ThomasEricB's icon.
As for screenshot, I don't think it will raise same issue while using Thumbnailer.lua as it was issue when using mpv_thumbnail_script only

**Comment by dexeonify** [comment]
Yes, use his icon font if you are installing his mpv_thumbnail_script version, use my icon font if you are using my version.

**Comment by lostb053** [comment]
Following your advice, I've set the mpv structure accordingly
> ```
> <your mpv profile folder>
> │   input.conf
> │   mpv.conf
> │
> ├── fonts/
> │   └─ modernx-osc-icon.ttf
> │
> ├── script-opts/
> │   ├─ osc.conf
> │   └─ thumbnailer.conf
> │
> └── scripts/
>      ├─ modernx.lua
>      ├─ Thumbnailer.lua
>      └─ Thumbnailer_Worker.lua
> ```

Right now I'm using your `Thumbnailer.lua` script and following your advice did the trick
> Did you went through the [config file](https://github.com/dexeonify/mpv-config/blob/main/script-opts/thumbnailer.conf) There's 2 options (auto_gen and auto_show) which controls that. Enable both settings if you want it to work out of the box.

Do you still need a screenshot?
> That's odd. My only guess is that the modernx-icon-font isn't in sync with modernx's version. A screenshot would help immensely though. Make sure to not mix my icon font with ThomasEricB's.

I would like to remind that I was then using ThomasEricB's script with your font, which might have been possible for icon conflicts

**Comment by dexeonify** [comment]
> I would like to remind that I was then using ThomasEricB's script with your font, which might have been possible for icon conflicts

Exactly.

> Do you still need a screenshot?

If everything's solved, then you don't need to. Feel free to close the issue too.

**Comment by lostb053** [comment]
Thnx for your help
