### ISSUE TITLE
[modernx] loop button

### ISSUE THREAD

**Issue by ma-zsola** [dexeonify/mpv-config#8]
Thank you for the osc script.
I would like to use a loop button on the osc, with playlist-loop functionality.
I succesfully implemented it, but I got stuck with the toggle function. The button doesn't gray out in "off" (inactive) state. It only changes when I play the next/previous track on the playlist.
Is there a way to change the button behavior on the fly when I press the button?

**Comment by dexeonify** [comment]
Looking at the code for `cy_audio` button, which updates immediately after clicking it, it appears that you have to store the property of `loop-playlist` somewhere in a global variable, and create a function that updates the property before the button is rendered.

There's a `update_tracklist()` function call before the `cy_audio` code, https://github.com/dexeonify/mpv-config/blob/b68269c7344e6eeae1ca91ac69245b7e2ea540d0/scripts/modernx.lua#L1664-L1667
which points to the following function: https://github.com/dexeonify/mpv-config/blob/b68269c7344e6eeae1ca91ac69245b7e2ea540d0/scripts/modernx.lua#L415-L438
As you can see, `tracks_mpv` and `tracks_osc` are global variables. Notice the comment too.
In the `cy_audio` code, left-clicking calls the `set_track()` function, while `ne.inactive` calls `get_track()`. Both which utilises the global variable `tracks_mpv`. https://github.com/dexeonify/mpv-config/blob/b68269c7344e6eeae1ca91ac69245b7e2ea540d0/scripts/modernx.lua#L1666-L1689

So yeah, not that easy after all.

**Comment by dexeonify** [comment]
Ok so I managed to work out a solution using the `state` table and the `observe_property()` function.
I tried to demonstrate it using `cy_audio` since you didn't provide me with your `playlist-loop` changes.
```patch
diff --git a/scripts/modernx.lua b/scripts/modernx.lua
index ffcae87..cac33c3 100644
--- a/scripts/modernx.lua
+++ b/scripts/modernx.lua
@@ -190,6 +190,7 @@ local state = {
     chapter_list = {},                      -- sorted by time
     lastvisibility = user_opts.visibility,  -- save last visibility on pause if showonpause
     subpos = 100,                           -- last value of sub-pos set by the user
+    loop_playlist = "no"
 }
 
 local window_control_box_width = 80
@@ -1667,7 +1668,7 @@ function osc_init()
     ne = new_element("cy_audio", "button")
 
     ne.enabled = (#tracks_osc.audio > 0)
-    ne.inactive = (get_track("audio") == 0)
+    ne.inactive = (state.loop_playlist == "no")
     ne.content = osc_icons.audio
     ne.tooltip_style = osc_styles.tooltip
     ne.tooltipF = function ()
@@ -1682,7 +1683,7 @@ function osc_init()
         return msg
     end
     ne.eventresponder["mbtn_left_up"] =
-        function () set_track("audio", 1) end
+        function () mp.commandv("cycle-values", "loop-playlist", "inf", "no") end
     ne.eventresponder["mbtn_right_up"] =
         function () set_track("audio", -1) end
     ne.eventresponder["shift+mbtn_left_down"] =
@@ -2528,6 +2529,12 @@ mp.observe_property("chapter-list", "native", function(_, list)
     request_init()
 end)
 mp.observe_property("sub-pos", "number", observe_subpos)
+mp.observe_property("loop-playlist", "string",
+    function(name, val)
+        state.loop_playlist = val
+        request_init()
+    end
+)
 
 mp.register_script_message("osc-message", show_message)
 mp.register_script_message("osc-chapterlist", function(dur)
```

**Comment by ma-zsola** [comment]
Wow, thank you very much for the help. It works like a charm. :-)

Here is my relevant code without your other additions:

```lua
   -- playlist loop
    ne = new_element("tog_loop", "button")

    ne.inactive = (state.loop_playlist == "no")
    ne.content = osc_icons.loop_pl
    ne.eventresponder["mbtn_left_up"] =
    function () 
        mp.commandv("cycle-values", "loop-playlist", "inf", "no") 
        if (state.loop_playlist == "no") then
            mp.osd_message("Playlist loop enabled")
        else
            mp.osd_message("Playlist loop disabled")
        end
    end
```
